### ISSUE TITLE
Motion model have no implementation?

### ISSUE THREAD

**Issue by vincentcheng62** [artofnothingness/mppic#108]
I am current using a 4-wheel differential drive AMR and trying to config the parameters for motion model like wheel_base
However when I look into the source code it seems there is no way to input such kinds of parameters and the implementation
in motion_models.hpp seems empty for class DiffDriveMotionModel

Any help on this? Many thanks!

**Comment by SteveMacenski** [comment]
This is a trajectory planner, not a low-level controller where we need that kind of information

**Comment by vincentcheng62** [comment]
But MPC need to know the kinematic model (like 4-wheel differential, tricycle...) in order to predict the trajectory, 
that is why MPC is Model Predictive controller. Am I correct?

**Comment by SteveMacenski** [comment]
The kinematic model is handled other ways through velocity limits and constraints. We don't need to know lower-level characteristics of the platform, we merely need to know what available actions the base can take in the base reference frame about its point of rotation. This is how we handle ackermann, omni, and differential dynamics and is pretty standard for trajectory planners. I'd recommend looking more into this topic.
