### ISSUE TITLE
migration to ros2 humble?

### ISSUE THREAD

**Issue by er1c-cartman** [artofnothingness/mppic#112]
Hi. i'm really interested in your works
is there any version of log mppi which have migrated to ros2 humble?

Best regards :)

**Comment by SteveMacenski** [comment]
This is deprecated in favor of the version in Nav2 which is being actively supported!

**Comment by er1c-cartman** [comment]
Hi
Yeah i mean to use log-mppi in nav2, specially in humble edition, i've changed noise part
But due to the log-mppi from ros1, https://github.com/IhabMohamed/log-MPPI_ros/blob/main/mppi_control/launch/mppi_launcher.launch,
i should change the std part and lambda part

The thing i want to ask you is when using log-mppi in ros2 humble with nav2, i guess i have to change the parameters of these

      vx_std: 0.5
      vy_std: 0.5
      wz_std: 0.8
      temperature: 0.25
      
but i don't have any idea to well form the parameter values
Ant suggestions?
