### ISSUE TITLE
Penalizing reversing?

### ISSUE THREAD

**Issue by SteveMacenski** [artofnothingness/mppic#2]
I see this PR in the other repo https://github.com/FastSense/mppic/pull/11

Is this worth pulling in here? While I haven't tested yet, it seemed like reversing was already not particularly a problem -- but I could be wrong if you're starting at a path heading the opposite from the robot heading so reversing would allow tracking the path without turning around.

**Comment by artofnothingness** [comment]
> it seemed like reversing was already not particularly a problem

I think it's not

This cost function could be added too, for preferring moving forward.
