### ISSUE TITLE
Add small gifs to readme

### ISSUE THREAD

**Issue by SteveMacenski** [artofnothingness/mppic#20]
The gifs are 27mb and 4mb, respectively. This is quite alot for cloning, it would be good to compress these to be smaller so that we don't have 31mb to download for the source

**Comment by artofnothingness** [comment]
Removed all binaries from the history. Later just add link to some hosting

**Comment by SteveMacenski** [comment]
OK

I know for instance if you drag the image into a github comment window (like this one) it will host + then show in mark down format the URL where its hosted. You can then copy paste that markdown block and use it in the readme. As far as I can tell, its permanent -- I have some other repos where I've done that and for years now the gifs/images are still showing.

**Comment by SteveMacenski** [comment]
![ezgif-4-0de8eb0f05](https://user-images.githubusercontent.com/14944147/165621789-9a008559-6c8d-430a-bda3-ed4df3f9c711.gif)

PR to add to readme
