### ISSUE TITLE
Critic scoring normalization

### ISSUE THREAD

**Issue by SteveMacenski** [artofnothingness/mppic#27]
Looking over the critics
- Goal Angle scores the differences in yaw angles
- Goal scores translational distances
- Obstacle scores normalized cost 0-1.0
- Path Angle scores differences in angles
- Approx / Ref Path are translational distances

Maybe it would be good to normalize these terms so that when we assign the weights its not proportional to absolute values? Let me know what you think, this is just a suggestion. I don't think its critical but a nice to have. 

But more consequentially, for the differences in angles, how are the angles normalized? They are setup as `abs(A - B)` which doesn't protect against wrap around to represent the shortest distance? `ros/angles` can help here https://github.com/ros/angles/blob/master/angles/include/angles/angles.h#L103-L106. That seems like more of a potential issue. Also in the prefer forward critic as well.

**Comment by artofnothingness** [comment]
That's nice idea to normalize these costs. Weights will start to have more determined meaning i guess.
Oh... this angles indeed requires normalization
