### ISSUE TITLE
Dynamic parameters lock kills the heartbeat

### ISSUE THREAD

**Issue by artofnothingness** [artofnothingness/mppic#37]
While robot moving try to change dynamic param. Get this error

```
[container_isolated-6] [INFO] [1649365719.116922575] [lifecycle_manager_navigation]: Have not received a heartbeat from controller_server.
[component_container_isolated-6] [ERROR] [1649365719.116979220] [lifecycle_manager_navigation]: CRITICAL FAILURE: SERVER controller_server IS DOWN after not receiving a heartbeat for 4000 ms. Shutting down related nodes
```

Reproduced on MPPI and DWB

**Comment by SteveMacenski** [comment]
@artofnothingness pull in nav2 main and it works now :smile: 

I changed an MPPI parameter while running with the current state and succeeded navigation. I then reverted the commit and then tried again and it failed. I readded the commit + locks in MPPI and works now.
