### ISSUE TITLE
Replace xtensor

### ISSUE THREAD

**Issue by artofnothingness** [artofnothingness/mppic#39]

**Comment by SteveMacenski** [comment]
Do you have some metrics / intuition on how much more performant it would be?

**Comment by artofnothingness** [comment]
I don't know exactly, but i had previously problems with xtensor views performance, and i also read some articles on their comparison ([this e.g](https://romanpoya.medium.com/a-look-at-the-performance-of-expression-templates-in-c-eigen-vs-blaze-vs-fastor-vs-armadillo-vs-2474ed38d982#:~:text=Eigen%20has%20almost%20become%20an,to%20Python%2C%20Julia%20and%20R.).)
That's why i don't use views in ReferenceTrajectoryCritic much.

i think to do some experiments in test branch later, then make comparison

**Comment by SteveMacenski** [comment]
That does look rather compelling, I'd agree!

**Comment by artofnothingness** [comment]
We need to make more profiling before claiming xtensor slow in some part

**Comment by SteveMacenski** [comment]
Don't we rather know that its too slow? Isn't that worth actually implementing in Eigen to find out? I don't see any downside of trying at least 1 other library, especially one like Eigen that is long term stable and mature

**Comment by artofnothingness** [comment]
@SteveMacenski 
I was thinking of reopening this after profiling/optimization stuffs. But might be it's not a good reason to close this temporary
Also i think that 2 iterations is too much for 20hz for current reference critic complexity. 
I think eigen port still actual anywaay.

You could try params in art branch, i optimized some parts, tweaked params. Now it works at 10-20ms in tb3simulation, and 8ms in benchmarks for all stuffs at my machine (4gen intel)

**Comment by artofnothingness** [comment]
@SteveMacenski i propose to stick to xtensor for cpu version for now. If we'r not using views in "for for for" loops it's performance quite ok. Eigen tensors way worse in terms of documentation and api, and i'm not sure that it gives us much even if rewrite everything. 
I have my suspicions that problem is in algorithmic complexity mostly. Benchmarks on **all** critics turned on gave me 8 ms on one iteration (batch 400, time_steps 15, path 50), but while simulation, and other stuffs it gave me about 20-30 ms. Could it be that other nav2 parts and gazebo took too much resources ?  We could try to optimizer most heavy critics + turn on xtensor multithreading capabilities + maybe parallelization of some parts by hand, then evaluate performance. i think we could easily get ok performance without switching to unsupported eigen module (tensors) 
Eigen port will take too much time, and it's not worth it.

**Comment by SteveMacenski** [comment]
Don't get me wrong, the rest of Nav2 isn't "free", but the controller typically is the most significant pull of resources in the entire stack, on par with the costmap updates. Those are the 2 heaviest operations by far. 

8ms is just the critics though, generating those trajectories and the other operations for pruning take some time (though I don't know how much?). The controller server doesn't really do a whole lot other than pass stuff to the plugins (here's the while loop that would be the steady state execution https://github.com/ros-planning/navigation2/blob/main/nav2_controller/src/controller_server.cpp#L374-L407) 

I'd be curious if you did logging / benchmarking off of `computeVelocityCommands` in total to separate out the contribution of the controller server overhead from the full of what the MPPI is doing what that would look like.

I think trying to turn on multithreading could be interesting. With 400 trajectories, that might be enough to justify a small thread pool.

20-30ms isn't terrible, but I wasn't even getting that before (though you'd retuned and reworked the critics, so maybe its different from the last time I used with it). It was regularly missing the 20hz (50ms) update times. If we were getting 20ms (50hz) on a standard laptop intel processor (like a mobile i5, 5-9th generation), I'd be perfectly happy with that.

**Comment by artofnothingness** [comment]
It was 8 ms on all optimizer stuffs (evalControl). PathHandler take less than 1ms.

**Comment by SteveMacenski** [comment]
Sorry for the delay, I was on vacation.

What's everything from `computeVelocityCommands` down? That would be the illustrative number. That's everything in this plugin (including the plugin itself) minus controller server overhead. If that's still around `8-10ms` but the loops are 20-30ms, then yes, that's something to be addressed in Nav2 itself. I'll say though I have other plugins in the controller server which I've tested up to 1kHz doing really basic geometric control.
