### ISSUE TITLE
unused variable ‘is_path_longer_than_trajectory’

### ISSUE THREAD

**Issue by padhupradheep** [artofnothingness/mppic#57]
Was planning to do some tuning for omni robots, while building got an issue. 

```
ros2_nav_ws/src/mppic/src/critics/path_align_critic.cpp:112:16: error: unused variable ‘is_path_longer_than_trajectory’ [-Werror=unused-variable]
  112 |           bool is_path_longer_than_trajectory = true;
```

Of course I can give a PR. but thought should report it here as well. 

But maybe this variable was planned for something ?

**Comment by artofnothingness** [comment]
Hi. Thanks for noticing. It's a typo from prev PR. Fixed in develop now, checkout plz.

**Comment by padhupradheep** [comment]
awesome! fixed now!
