### ISSUE TITLE
Incompatible dimension of arrays, compile in DEBUG for more info

### ISSUE THREAD

**Issue by padhupradheep** [artofnothingness/mppic#58]
I'm trying to use the "Omni" option for the motion_model parameter, but I get this error shown in the issue topic, when I try to send the goal. I just use the same parameters from the readme except the motion model. 

Is there something, I'm missing?

**Comment by artofnothingness** [comment]
Can you compile in debug and run this again, then show error message ?

**Comment by padhupradheep** [comment]
```
[New Thread 0x7fffccff9700 (LWP 41877)]
[INFO] [1654604831.693420980] [controller_server]: Received a goal, begin computing control effort.
[ERROR] [1654604831.784314302] [controller_server]: Action server failed while executing action callback: "Incompatible dimension of arrays, compile in DEBUG for more info"
[WARN] [1654604831.784357422] [controller_server]: [follow_path] [ActionServer] Aborting handle.
```

I just did a `colcon --log-level debug build` and just ran the usual steps! Of course with a GDB (just in case, if there is something that I can find over there as well)

maybe it is just something from xtensor?

**Comment by artofnothingness** [comment]
I mean
`colcon build --cmake-args -DCMAKE_BUILD_TYPE=DEBUG`

**Comment by artofnothingness** [comment]
> maybe it is just something from xtensor?

No, some operations of xtensor was used for non compatiable arrays. You could just wait until i find a bug, but a little later

**Comment by padhupradheep** [comment]
> colcon build --cmake-args -DCMAKE_BUILD_TYPE=DEBUG

```
 [controller_server]: Action server failed while executing action callback: "Incompatible dimension of arrays:
 LHS shape = (18446744073709551615, 15, 3, )
 RHS shape = (300, 15, 2, )"

```
> You could just wait until i find a bug, but a little later

I can wait!

**Comment by artofnothingness** [comment]
@padhupradheep  Must be fixed now
