### ISSUE TITLE
Require model_dt = control_frequency?

### ISSUE THREAD

**Issue by SteveMacenski** [artofnothingness/mppic#66]
That would help with stability if users couldn't define some model_dt != control_frequency so when we apply the control shift it doesn't shift by the right amount as the next starting point. We should just straight up require that to be true

**Comment by SteveMacenski** [comment]
That could be contributing to non-smoothness. What do you think?

**Comment by artofnothingness** [comment]
That could help a little, basically that shift helps with initial approximation on the next step, but without testing, it's hard to say.

**Comment by artofnothingness** [comment]
With extremely high hz, i don' think we must strictly require equality, model could plan by higher dt and it's ok, unless we prove opposite. higher model_dt implies less prediction time steps required for longer trajectory. And it could be more robust in some cases probably (why should we consider not constant speed at 40 hz, even if we replaning that fast.
