### ISSUE TITLE
CMake Error at benchmark/CMakeLists.txt:1 (find_package):

### ISSUE THREAD

**Issue by padhupradheep** [artofnothingness/mppic#69]
```
CMake Error at benchmark/CMakeLists.txt:1 (find_package): 
By not providing "Findbenchmark.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "benchmark", but CMake did not find one.

  Could not find a package configuration file provided by "benchmark" with
  any of the following names:

```

Is there something missing in readme after the updates? 

I'm trying in Galactic.. 

Sorry if I missed something blindly!

**Comment by padhupradheep** [comment]
okay! need to install

`sudo apt-get install ros-galactic-performance-test-fixture`

Would be nice, if added as part of the readme.. 

leaving to the maintainers to decide on closing the issue.

**Comment by SteveMacenski** [comment]
Rosdep would have solved it too!
